### ISSUE TITLE
Epic: Friends-Experience

### ISSUE THREAD

**Issue by ski7777** [engelsystem/engelsystem#1493]
Angels have friends and the like them. I want to help angels to find their friends in shifts or even work together as dream teams.

Steps needed to implement this as roughly discussed as 38C3 with @MyIgel:
- [ ] **Friendship**
  - [ ] users can request friendship with other user
  - [ ] users can accept incoming friendship request
  - [ ] users can reject incoming friendship request
  - [ ] users can abort outgoing friendship request
  - [ ] users can block other users
- [ ] **Friend shifts**
  - [ ] see current/upcoming/last shift of befriended person
  - [ ] see timetable for befriended person
  - [ ] filter for shifts with friends registered for shift
  - [ ] notify users when friends register for a shift and the users is eligible for the shift and has no collisions
